# Create a dictionary of words to be used in the game, with "Categories" as keys
# and corresponding words as values
# N.B. Dictionary derived from: http://www.enchantedlearning.com/wordlist/
var word_dictionary = {
    "Animals" : [],
    "Art" : [],
    "Astronomy" : [],
    "Beach" : [],
    "Biomes" : [],
    "Body" : [],
    "Carpenter's Tools" : [],
    "Christmas" : [],
    "Colors" : [],
    "Computers" : [],
    "Cooking Tools" : [],
    "Country Names" : [],
    "Desserts" : [],
    "Dogs" : [],
    "Elements" : [],
    "Fields of Science" : [],
    "Fish" : [],
    "Flowers" : [],
    "Food" : [],
    "Fruit" : [],
    "Herbs and Spices" : [],
    "Holidays" : [],
    "Insects" : [],
    "Languages" : [],
    "Measurement" : [],
    "Metals" : [],
    "Musical Instruments" : [],
    "Plants" : [],
    "Rocks and Minerals" : [],
    "Science and Lab" : [],
    "Shapes" : [],
    "Sports" : [],
    "Vegetables" : [],
    "Weather" : [],
}
